// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouosjhxcyigsrifrzqcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91b3NqaHhjeWlnc3JpZnJ6cWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTIyNTMsImV4cCI6MjA2MTY4ODI1M30.ZzTFBqawPdLkWDdIWLpOycwgGO3efPoEyYNsT9AfVhw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);